/* This file was generated by SableCC (http://www.sablecc.org/). */

package malgol.node;

import malgol.analysis.*;

@SuppressWarnings("nls")
public final class ASomeDeclList extends PDeclList
{
    private PDecl _decl_;
    private PDeclList _declList_;

    public ASomeDeclList()
    {
        // Constructor
    }

    public ASomeDeclList(
        @SuppressWarnings("hiding") PDecl _decl_,
        @SuppressWarnings("hiding") PDeclList _declList_)
    {
        // Constructor
        setDecl(_decl_);

        setDeclList(_declList_);

    }

    @Override
    public Object clone()
    {
        return new ASomeDeclList(
            cloneNode(this._decl_),
            cloneNode(this._declList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomeDeclList(this);
    }

    public PDecl getDecl()
    {
        return this._decl_;
    }

    public void setDecl(PDecl node)
    {
        if(this._decl_ != null)
        {
            this._decl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decl_ = node;
    }

    public PDeclList getDeclList()
    {
        return this._declList_;
    }

    public void setDeclList(PDeclList node)
    {
        if(this._declList_ != null)
        {
            this._declList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decl_)
            + toString(this._declList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decl_ == child)
        {
            this._decl_ = null;
            return;
        }

        if(this._declList_ == child)
        {
            this._declList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decl_ == oldChild)
        {
            setDecl((PDecl) newChild);
            return;
        }

        if(this._declList_ == oldChild)
        {
            setDeclList((PDeclList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
